### ISSUE TITLE
Failed to parse KDL

### ISSUE THREAD

**Issue by haunt98** [hougesen/kdlfmt#47]
I use Zellij with following config:

```kdl
theme "catppuccin-mocha"
default_layout "compact"
default_mode "locked"
on_force_close "quit"
simplified_ui true

ui {
    pane_frames {
        hide_session_name true
    }
}

keybinds {
shared {
        bind "Alt p" { SwitchFocus; }
        bind "Alt o" { NewTab; }
        bind "Alt ]" { GoToNextTab; }
        bind "Alt [" { GoToPreviousTab; }
        bind "Alt n" { NewPane; }
        bind "Alt m" { NewPane "Down"; }
    }
}
```

https://kdl-play.danini.dev/ check my config with no problem, also Zellij can load it but `kdlfmt` fails to parse it.

```txt
❯ kdlfmt check ~/.config/zellij/config.kdl
Error parsing file '/Users/anon/.config/zellij/config.kdl' - Failed to parse KDL.
```

**Comment by hougesen** [comment]
kdlfmt is simply a wrapper around the official kdl crate for Rust  ([kdl-rs](https://github.com/kdl-org/kdl-rs)), which sadly does not have a cli. Any formatting/parsing errors should be reported there.

The error you are getting is because the kdl-rs crate is in the progress of being rewritten to kdl specification v2, but zellij uses kdl v1.

I have downgraded the kdl-rs crate back to the latest stable version using kdl v1, since most kdlfmt users are most likely using it for zellij configuration. Installing the newest version of kdlfmt should fix your issue 😄

**Comment by haunt98** [comment]
Thank you @hougesen l, til there is 2 version of kdl.
